const tasks = [
  { id: "str-pushups-30", statType: "STR", difficulty: "EASY", sortOrder: 1,
    title: "30 şınav çek", description: "Tek sette olmasa da olur, form bozulmasın" },
  { id: "str-plank-5", statType: "STR", difficulty: "MEDIUM", sortOrder: 2,
    title: "5 dakika plank", description: "Toplamda, setlere bölerek" },
  { id: "str-weights-45", statType: "STR", difficulty: "MEDIUM", sortOrder: 3,
    title: "45 dakika ağırlık antrenmanı", description: "Büyük kas gruplarına odaklan" },
  { id: "str-run-10k", statType: "STR", difficulty: "HARD", sortOrder: 4,
    title: "10 km koş", description: "Tek seferde, tempo serbest" },
  { id: "str-hike-day", statType: "STR", difficulty: "EPIC", sortOrder: 5,
    title: "Bir günlük doğa yürüyüşü", description: "En az 6 saat, sırt çantalı" },

  { id: "dex-stretch-15", statType: "DEX", difficulty: "EASY", sortOrder: 6,
    title: "15 dakika esneme", description: "Sabah veya akşam, yavaş tempoda" },
  { id: "dex-balance-10", statType: "DEX", difficulty: "EASY", sortOrder: 7,
    title: "10 dakika denge çalışması", description: "Tek ayak, göz kapalı deneyebilirsin" },
  { id: "dex-instrument-45", statType: "DEX", difficulty: "MEDIUM", sortOrder: 8,
    title: "45 dakika enstrüman çalış", description: "Teknik egzersiz veya parça" },
  { id: "dex-handcraft-new", statType: "DEX", difficulty: "MEDIUM", sortOrder: 9,
    title: "Yeni bir el becerisi öğren", description: "Düğüm, origami, yemek tekniği — video izleyip uygula" },
  { id: "dex-repair", statType: "DEX", difficulty: "HARD", sortOrder: 10,
    title: "Bir şey tamir et veya yap", description: "El aleti kullan, çalışır hale getir" },

  { id: "con-water-2500", statType: "CON", difficulty: "EASY", sortOrder: 11,
    title: "2.5 litre su iç", description: "Gün boyunca dağıtarak" },
  { id: "con-sleep-8", statType: "CON", difficulty: "MEDIUM", sortOrder: 12,
    title: "8 saat uyu", description: "Aynı saatte yat, alarm kurmadan uyan" },
  { id: "con-no-sugar", statType: "CON", difficulty: "MEDIUM", sortOrder: 13,
    title: "Şekersiz gün geçir", description: "İşlenmiş şeker, tatlı, gazlı içecek yok" },
  { id: "con-cold-shower", statType: "CON", difficulty: "HARD", sortOrder: 14,
    title: "5 dakika soğuk duş", description: "Ilıkla başla, son 5 dakika soğuk" },
  { id: "con-fasting-16", statType: "CON", difficulty: "HARD", sortOrder: 15,
    title: "16 saat aralıklı oruç", description: "Sadece su, çay, sade kahve" },

  { id: "int-read-30p", statType: "INT", difficulty: "EASY", sortOrder: 16,
    title: "30 sayfa oku", description: "Kurgu dışı tercih et" },
  { id: "int-article-summary", statType: "INT", difficulty: "EASY", sortOrder: 17,
    title: "Bir makale oku ve özetle", description: "Kendi cümlelerinle 5 satır yaz" },
  { id: "int-deep-work-2h", statType: "INT", difficulty: "MEDIUM", sortOrder: 18,
    title: "2 saat kesintisiz çalış", description: "Telefon başka odada, tek konu" },
  { id: "int-teach-someone", statType: "INT", difficulty: "MEDIUM", sortOrder: 19,
    title: "Bir konuyu birine anlat", description: "Anlatabiliyorsan anlamışsındır" },
  { id: "int-small-project", statType: "INT", difficulty: "HARD", sortOrder: 20,
    title: "Küçük bir proje bitir", description: "Öğrendiğini uygula, çalışır hale getir" },
  { id: "int-build-in-a-day", statType: "INT", difficulty: "EPIC", sortOrder: 21,
    title: "Bir günde yeni bir şey inşa et", description: "Prototip, deney, uygulama — akşama kadar" },

  { id: "wis-meditate-10", statType: "WIS", difficulty: "EASY", sortOrder: 22,
    title: "10 dakika meditasyon", description: "Nefese odaklan, sayma" },
  { id: "wis-journal", statType: "WIS", difficulty: "EASY", sortOrder: 23,
    title: "Günlük yaz", description: "Bugün ne oldu, ne hissettin, ne öğrendin" },
  { id: "wis-morning-pages", statType: "WIS", difficulty: "MEDIUM", sortOrder: 24,
    title: "Sabah 3 sayfa yaz", description: "Uyanır uyanmaz, filtresiz, aklından geçeni" },
  { id: "wis-screenfree-4h", statType: "WIS", difficulty: "HARD", sortOrder: 25,
    title: "Ekransız 4 saat geçir", description: "Telefon, bilgisayar, TV yok" },
  { id: "wis-screenfree-day", statType: "WIS", difficulty: "EPIC", sortOrder: 26,
    title: "Bir günü tamamen ekransız geçir", description: "Uyanıştan uykuya, acil durumlar hariç" },

  { id: "cha-call-friend", statType: "CHA", difficulty: "EASY", sortOrder: 27,
    title: "Bir arkadaşını ara", description: "Mesaj değil, sesli konuş, en az 15 dakika" },
  { id: "cha-talk-stranger", statType: "CHA", difficulty: "MEDIUM", sortOrder: 28,
    title: "Tanımadığın biriyle sohbet başlat", description: "Kasada, otobüste, kuyrukta" },
  { id: "cha-presentation-rehearsal", statType: "CHA", difficulty: "MEDIUM", sortOrder: 29,
    title: "Sunum provası yap", description: "Yüksek sesle, baştan sona, kamera karşısında" },
  { id: "cha-public-speaking", statType: "CHA", difficulty: "HARD", sortOrder: 30,
    title: "Topluluk önünde konuş", description: "Toplantı, seminer, etkinlik — en az 10 kişi" },
];

module.exports = { tasks };
