const tasks = [
  { id: "str-pushups-30", statType: "STR", difficulty: "EASY", sortOrder: 1,
    title: "30 şınav çek", description: "Tek sette olmasa da olur, form bozulmasın",
    titleEn: "Do 30 push-ups", descriptionEn: "Sets are fine, just keep your form" },
  { id: "str-squats-50", statType: "STR", difficulty: "EASY", sortOrder: 2,
    title: "50 squat yap", description: "Dizler parmak ucunu geçmesin",
    titleEn: "Do 50 squats", descriptionEn: "Keep your knees behind your toes" },
  { id: "str-walk-8k", statType: "STR", difficulty: "EASY", sortOrder: 3,
    title: "8.000 adım yürü", description: "Gün içine yayabilirsin",
    titleEn: "Walk 8,000 steps", descriptionEn: "Spread them across the day" },
  { id: "str-stairs-10", statType: "STR", difficulty: "EASY", sortOrder: 4,
    title: "10 kat merdiven çık", description: "Asansörü boş ver",
    titleEn: "Climb 10 flights of stairs", descriptionEn: "Skip the elevator" },
  { id: "str-carry-groceries", statType: "STR", difficulty: "EASY", sortOrder: 5,
    title: "Alışverişi elde taşı", description: "Araba yok, sadece sen ve çantalar",
    titleEn: "Carry the groceries home", descriptionEn: "No car, just you and the bags" },
  { id: "str-plank-5", statType: "STR", difficulty: "MEDIUM", sortOrder: 6,
    title: "5 dakika plank", description: "Toplamda, setlere bölerek",
    titleEn: "Hold a 5-minute plank", descriptionEn: "Total time, split into sets" },
  { id: "str-weights-45", statType: "STR", difficulty: "MEDIUM", sortOrder: 7,
    title: "45 dakika ağırlık antrenmanı", description: "Büyük kas gruplarına odaklan",
    titleEn: "45 minutes of weight training", descriptionEn: "Focus on the big muscle groups" },
  { id: "str-pullups-30", statType: "STR", difficulty: "MEDIUM", sortOrder: 8,
    title: "30 barfiks çek", description: "Lastikle destek alabilirsin",
    titleEn: "Do 30 pull-ups", descriptionEn: "A resistance band counts" },
  { id: "str-run-5k", statType: "STR", difficulty: "MEDIUM", sortOrder: 9,
    title: "5 km koş", description: "Tempo serbest, yürüyerek bölme",
    titleEn: "Run 5 km", descriptionEn: "Any pace, but do not walk it" },
  { id: "str-swim-1k", statType: "STR", difficulty: "MEDIUM", sortOrder: 10,
    title: "1 km yüz", description: "Stil serbest, mola verebilirsin",
    titleEn: "Swim 1 km", descriptionEn: "Any stroke, breaks allowed" },
  { id: "str-run-10k", statType: "STR", difficulty: "HARD", sortOrder: 11,
    title: "10 km koş", description: "Tek seferde, tempo serbest",
    titleEn: "Run 10 km", descriptionEn: "One go, any pace" },
  { id: "str-bike-40k", statType: "STR", difficulty: "HARD", sortOrder: 12,
    title: "40 km bisiklet sür", description: "Rampalardan kaçma",
    titleEn: "Cycle 40 km", descriptionEn: "Do not dodge the hills" },
  { id: "str-heavy-session", statType: "STR", difficulty: "HARD", sortOrder: 13,
    title: "Ağır antrenman günü", description: "Kişisel rekoruna yaklaş, ısınmayı atlama",
    titleEn: "Push a heavy training day", descriptionEn: "Chase a personal best, but warm up first" },
  { id: "str-hike-day", statType: "STR", difficulty: "EPIC", sortOrder: 14,
    title: "Bir günlük doğa yürüyüşü", description: "En az 6 saat, sırt çantalı",
    titleEn: "Spend a day hiking", descriptionEn: "At least 6 hours, pack on your back" },
  { id: "str-race-day", statType: "STR", difficulty: "EPIC", sortOrder: 15,
    title: "Bir yarışa katıl", description: "Koşu, bisiklet, triatlon — kayıt ol ve bitir",
    titleEn: "Finish a race", descriptionEn: "Running, cycling, triathlon: sign up and cross the line" },

  { id: "dex-stretch-15", statType: "DEX", difficulty: "EASY", sortOrder: 16,
    title: "15 dakika esneme", description: "Sabah veya akşam, yavaş tempoda",
    titleEn: "Stretch for 15 minutes", descriptionEn: "Morning or evening, take it slow" },
  { id: "dex-balance-10", statType: "DEX", difficulty: "EASY", sortOrder: 17,
    title: "10 dakika denge çalışması", description: "Tek ayak, göz kapalı deneyebilirsin",
    titleEn: "10 minutes of balance work", descriptionEn: "One leg, and try it with your eyes closed" },
  { id: "dex-mobility-morning", statType: "DEX", difficulty: "EASY", sortOrder: 18,
    title: "Sabah hareketlilik rutini", description: "Eklemleri baştan aşağı çalıştır, 10 dakika",
    titleEn: "Run a morning mobility routine", descriptionEn: "Every joint, top to bottom, 10 minutes" },
  { id: "dex-handwriting", statType: "DEX", difficulty: "EASY", sortOrder: 19,
    title: "Bir sayfa elle yaz", description: "Klavye yok, okunaklı olsun",
    titleEn: "Write a page by hand", descriptionEn: "No keyboard, and keep it legible" },
  { id: "dex-coordination-15", statType: "DEX", difficulty: "EASY", sortOrder: 20,
    title: "15 dakika koordinasyon çalış", description: "Jonglörlük, ip atlama, top sektirme",
    titleEn: "15 minutes of coordination work", descriptionEn: "Juggling, jump rope, ball control" },
  { id: "dex-instrument-45", statType: "DEX", difficulty: "MEDIUM", sortOrder: 21,
    title: "45 dakika enstrüman çalış", description: "Teknik egzersiz veya parça",
    titleEn: "Practise an instrument for 45 minutes", descriptionEn: "Technique drills or a piece" },
  { id: "dex-handcraft-new", statType: "DEX", difficulty: "MEDIUM", sortOrder: 22,
    title: "Yeni bir el becerisi öğren", description: "Düğüm, origami, yemek tekniği — video izleyip uygula",
    titleEn: "Learn a new hand skill", descriptionEn: "A knot, origami, a kitchen technique: watch it and do it" },
  { id: "dex-cook-new-recipe", statType: "DEX", difficulty: "MEDIUM", sortOrder: 23,
    title: "Yeni bir tarif pişir", description: "Daha önce yapmadığın bir şey, baştan sona",
    titleEn: "Cook a new recipe", descriptionEn: "Something you have never made, start to finish" },
  { id: "dex-draw-30", statType: "DEX", difficulty: "MEDIUM", sortOrder: 24,
    title: "30 dakika çizim yap", description: "Kopyalama değil, gözlemleyerek çiz",
    titleEn: "Draw for 30 minutes", descriptionEn: "From observation, not from a copy" },
  { id: "dex-skill-sport", statType: "DEX", difficulty: "MEDIUM", sortOrder: 25,
    title: "Bir beceri sporu antrenmanı", description: "Tırmanış, dans, dövüş sanatı, tenis",
    titleEn: "Train a skill sport", descriptionEn: "Climbing, dance, martial arts, tennis" },
  { id: "dex-repair", statType: "DEX", difficulty: "HARD", sortOrder: 26,
    title: "Bir şey tamir et veya yap", description: "El aleti kullan, çalışır hale getir",
    titleEn: "Fix or make something", descriptionEn: "Use real tools and get it working" },
  { id: "dex-build-furniture", statType: "DEX", difficulty: "HARD", sortOrder: 27,
    title: "Bir mobilya kur veya yap", description: "Alet çantasını aç, sonuna kadar git",
    titleEn: "Assemble or build a piece of furniture", descriptionEn: "Open the toolbox and see it through" },
  { id: "dex-perform-piece", statType: "DEX", difficulty: "HARD", sortOrder: 28,
    title: "Bir parçayı hatasız çal", description: "Ezbere, baştan sona, duraksamadan",
    titleEn: "Perform a piece cleanly", descriptionEn: "From memory, start to finish, no stops" },
  { id: "dex-craft-project", statType: "DEX", difficulty: "EPIC", sortOrder: 29,
    title: "Elinle bir şey üret", description: "Günler süren bir iş: dolap, elbise, enstrüman",
    titleEn: "Craft something with your hands", descriptionEn: "A multi-day build: a cabinet, a garment, an instrument" },
  { id: "dex-perform-public", statType: "DEX", difficulty: "EPIC", sortOrder: 30,
    title: "Sahnede performans sergile", description: "Konser, gösteri, turnuva — izleyici karşısında",
    titleEn: "Perform in front of an audience", descriptionEn: "A gig, a show, a tournament" },

  { id: "con-water-2500", statType: "CON", difficulty: "EASY", sortOrder: 31,
    title: "2.5 litre su iç", description: "Gün boyunca dağıtarak",
    titleEn: "Drink 2.5 litres of water", descriptionEn: "Spread across the day" },
  { id: "con-no-screen-bed", statType: "CON", difficulty: "EASY", sortOrder: 32,
    title: "Yatakta telefon yok", description: "Son bir saati ekransız geçir",
    titleEn: "No phone in bed", descriptionEn: "Screen-free for the last hour" },
  { id: "con-vegetables-5", statType: "CON", difficulty: "EASY", sortOrder: 33,
    title: "Beş porsiyon sebze meyve ye", description: "Renk çeşidi tut",
    titleEn: "Eat five servings of fruit and veg", descriptionEn: "Mix up the colours" },
  { id: "con-morning-sun", statType: "CON", difficulty: "EASY", sortOrder: 34,
    title: "Sabah 15 dakika dışarı çık", description: "Uyandıktan sonraki ilk saat içinde",
    titleEn: "Get 15 minutes of morning light", descriptionEn: "Within an hour of waking" },
  { id: "con-wind-down", statType: "CON", difficulty: "EASY", sortOrder: 35,
    title: "Uyumadan önce gevşe", description: "10 dakika nefes çalışması veya esneme",
    titleEn: "Wind down before bed", descriptionEn: "10 minutes of breathing or stretching" },
  { id: "con-sleep-8", statType: "CON", difficulty: "MEDIUM", sortOrder: 36,
    title: "8 saat uyu", description: "Aynı saatte yat, alarm kurmadan uyan",
    titleEn: "Sleep eight hours", descriptionEn: "Same bedtime, wake without an alarm" },
  { id: "con-no-sugar", statType: "CON", difficulty: "MEDIUM", sortOrder: 37,
    title: "Şekersiz gün geçir", description: "İşlenmiş şeker, tatlı, gazlı içecek yok",
    titleEn: "Go a day without sugar", descriptionEn: "No processed sugar, sweets or soft drinks" },
  { id: "con-no-alcohol", statType: "CON", difficulty: "MEDIUM", sortOrder: 38,
    title: "Alkolsüz gün geçir", description: "Tek damla yok",
    titleEn: "Go a day without alcohol", descriptionEn: "Not a drop" },
  { id: "con-no-caffeine", statType: "CON", difficulty: "MEDIUM", sortOrder: 39,
    title: "Kafeinsiz gün geçir", description: "Kahve, çay, enerji içeceği yok",
    titleEn: "Go a day without caffeine", descriptionEn: "No coffee, tea or energy drinks" },
  { id: "con-meal-prep", statType: "CON", difficulty: "MEDIUM", sortOrder: 40,
    title: "Haftalık yemeğini hazırla", description: "En az üç öğün, önceden pişir",
    titleEn: "Prep your meals for the week", descriptionEn: "At least three meals, cooked ahead" },
  { id: "con-cold-shower", statType: "CON", difficulty: "HARD", sortOrder: 41,
    title: "5 dakika soğuk duş", description: "Ilıkla başla, son 5 dakika soğuk",
    titleEn: "Take a 5-minute cold shower", descriptionEn: "Start warm, finish with five cold minutes" },
  { id: "con-fasting-16", statType: "CON", difficulty: "HARD", sortOrder: 42,
    title: "16 saat aralıklı oruç", description: "Sadece su, çay, sade kahve",
    titleEn: "Fast for 16 hours", descriptionEn: "Water, tea and black coffee only" },
  { id: "con-same-wake-week", statType: "CON", difficulty: "HARD", sortOrder: 43,
    title: "Bir hafta aynı saatte kalk", description: "Hafta sonu dahil, ertelemesiz",
    titleEn: "Wake at the same time for a week", descriptionEn: "Weekends included, no snooze" },
  { id: "con-fasting-24", statType: "CON", difficulty: "EPIC", sortOrder: 44,
    title: "24 saat oruç tut", description: "Sadece su. Sağlığın elverdiği ölçüde",
    titleEn: "Fast for 24 hours", descriptionEn: "Water only, and only if your health allows" },
  { id: "con-quit-month", statType: "CON", difficulty: "EPIC", sortOrder: 45,
    title: "Bir alışkanlığı bir ay bırak", description: "Sigara, şeker, alkol — otuz gün, taviz yok",
    titleEn: "Drop a habit for a month", descriptionEn: "Smoking, sugar, alcohol: thirty days, no exceptions" },

  { id: "int-read-30p", statType: "INT", difficulty: "EASY", sortOrder: 46,
    title: "30 sayfa oku", description: "Kurgu dışı tercih et",
    titleEn: "Read 30 pages", descriptionEn: "Non-fiction preferred" },
  { id: "int-article-summary", statType: "INT", difficulty: "EASY", sortOrder: 47,
    title: "Bir makale oku ve özetle", description: "Kendi cümlelerinle 5 satır yaz",
    titleEn: "Read an article and summarise it", descriptionEn: "Five lines, in your own words" },
  { id: "int-new-words-5", statType: "INT", difficulty: "EASY", sortOrder: 48,
    title: "Beş yeni kelime öğren", description: "Cümle içinde kullan, not al",
    titleEn: "Learn five new words", descriptionEn: "Use each in a sentence and write it down" },
  { id: "int-documentary", statType: "INT", difficulty: "EASY", sortOrder: 49,
    title: "Bir belgesel izle", description: "Bitince aklında kalan üç şeyi not et",
    titleEn: "Watch a documentary", descriptionEn: "Note three things when it ends" },
  { id: "int-puzzle-30", statType: "INT", difficulty: "EASY", sortOrder: 50,
    title: "30 dakika bulmaca çöz", description: "Satranç, sudoku, mantık problemi",
    titleEn: "Solve puzzles for 30 minutes", descriptionEn: "Chess, sudoku, logic problems" },
  { id: "int-deep-work-2h", statType: "INT", difficulty: "MEDIUM", sortOrder: 51,
    title: "2 saat kesintisiz çalış", description: "Telefon başka odada, tek konu",
    titleEn: "Work two hours without a break", descriptionEn: "Phone in another room, one subject" },
  { id: "int-teach-someone", statType: "INT", difficulty: "MEDIUM", sortOrder: 52,
    title: "Bir konuyu birine anlat", description: "Anlatabiliyorsan anlamışsındır",
    titleEn: "Explain a topic to someone", descriptionEn: "If you can teach it, you understand it" },
  { id: "int-language-lesson", statType: "INT", difficulty: "MEDIUM", sortOrder: 53,
    title: "Yabancı dil çalış", description: "45 dakika, konuşma pratiği dahil",
    titleEn: "Study a foreign language", descriptionEn: "45 minutes, speaking practice included" },
  { id: "int-write-1000", statType: "INT", difficulty: "MEDIUM", sortOrder: 54,
    title: "Bin kelime yaz", description: "Deneme, blog, bölüm — bitir",
    titleEn: "Write a thousand words", descriptionEn: "Essay, blog post, chapter: finish it" },
  { id: "int-course-module", statType: "INT", difficulty: "MEDIUM", sortOrder: 55,
    title: "Bir ders modülü bitir", description: "Online kurs veya üniversite dersi, sonuna kadar",
    titleEn: "Finish a course module", descriptionEn: "Online or in class, all the way through" },
  { id: "int-small-project", statType: "INT", difficulty: "HARD", sortOrder: 56,
    title: "Küçük bir proje bitir", description: "Öğrendiğini uygula, çalışır hale getir",
    titleEn: "Finish a small project", descriptionEn: "Apply what you learned and make it work" },
  { id: "int-book-finish", statType: "INT", difficulty: "HARD", sortOrder: 57,
    title: "Bir kitabı bitir", description: "Baştan sona, atlamadan",
    titleEn: "Finish a book", descriptionEn: "Cover to cover, no skimming" },
  { id: "int-research-writeup", statType: "INT", difficulty: "HARD", sortOrder: 58,
    title: "Bir konuyu araştır ve yaz", description: "Kaynak topla, kendi sonucunu çıkar",
    titleEn: "Research a topic and write it up", descriptionEn: "Gather sources, land your own conclusion" },
  { id: "int-build-in-a-day", statType: "INT", difficulty: "EPIC", sortOrder: 59,
    title: "Bir günde yeni bir şey inşa et", description: "Prototip, deney, uygulama — akşama kadar",
    titleEn: "Build something new in a day", descriptionEn: "A prototype, an experiment, an app: done by evening" },
  { id: "int-ship-project", statType: "INT", difficulty: "EPIC", sortOrder: 60,
    title: "Bir projeyi yayına al", description: "Başkalarının kullanabileceği hale getir",
    titleEn: "Ship a project", descriptionEn: "Put it where other people can use it" },

  { id: "wis-meditate-10", statType: "WIS", difficulty: "EASY", sortOrder: 61,
    title: "10 dakika meditasyon", description: "Nefese odaklan, sayma",
    titleEn: "Meditate for 10 minutes", descriptionEn: "Follow the breath, do not count" },
  { id: "wis-journal", statType: "WIS", difficulty: "EASY", sortOrder: 62,
    title: "Günlük yaz", description: "Bugün ne oldu, ne hissettin, ne öğrendin",
    titleEn: "Write in your journal", descriptionEn: "What happened, what you felt, what you learned" },
  { id: "wis-gratitude-3", statType: "WIS", difficulty: "EASY", sortOrder: 63,
    title: "Üç şey için şükret", description: "Yaz, aklından geçirmekle yetinme",
    titleEn: "Name three things you are grateful for", descriptionEn: "Write them down, do not just think them" },
  { id: "wis-walk-no-phone", statType: "WIS", difficulty: "EASY", sortOrder: 64,
    title: "Telefonsuz yürüyüş yap", description: "20 dakika, kulaklık da yok",
    titleEn: "Take a walk without your phone", descriptionEn: "20 minutes, headphones off too" },
  { id: "wis-single-task-hour", statType: "WIS", difficulty: "EASY", sortOrder: 65,
    title: "Bir saat tek işe odaklan", description: "Bildirimler kapalı, fazladan sekme yok",
    titleEn: "Spend an hour on one thing", descriptionEn: "Notifications off, no extra tabs" },
  { id: "wis-morning-pages", statType: "WIS", difficulty: "MEDIUM", sortOrder: 66,
    title: "Sabah 3 sayfa yaz", description: "Uyanır uyanmaz, filtresiz, aklından geçeni",
    titleEn: "Write three pages each morning", descriptionEn: "Straight after waking, unfiltered" },
  { id: "wis-meditate-30", statType: "WIS", difficulty: "MEDIUM", sortOrder: 67,
    title: "30 dakika meditasyon", description: "Tek oturuşta, zamanlayıcıyla",
    titleEn: "Meditate for 30 minutes", descriptionEn: "One sitting, timer on" },
  { id: "wis-week-review", statType: "WIS", difficulty: "MEDIUM", sortOrder: 68,
    title: "Haftanı gözden geçir", description: "Ne işe yaradı, ne yaramadı, ne değişecek",
    titleEn: "Review your week", descriptionEn: "What worked, what did not, what changes" },
  { id: "wis-hard-conversation", statType: "WIS", difficulty: "MEDIUM", sortOrder: 69,
    title: "Ertelediğin konuşmayı yap", description: "Kaçındığın konu neyse, aç",
    titleEn: "Have the conversation you have been avoiding", descriptionEn: "Whatever the topic is, open it" },
  { id: "wis-nature-2h", statType: "WIS", difficulty: "MEDIUM", sortOrder: 70,
    title: "İki saat doğada kal", description: "Orman, sahil, tepe — telefon cepte",
    titleEn: "Spend two hours in nature", descriptionEn: "Forest, shore, hilltop, phone in your pocket" },
  { id: "wis-screenfree-4h", statType: "WIS", difficulty: "HARD", sortOrder: 71,
    title: "Ekransız 4 saat geçir", description: "Telefon, bilgisayar, TV yok",
    titleEn: "Go four hours without a screen", descriptionEn: "No phone, no computer, no TV" },
  { id: "wis-social-media-week", statType: "WIS", difficulty: "HARD", sortOrder: 72,
    title: "Bir hafta sosyal medyasız", description: "Uygulamaları sil, tarayıcıdan da girme",
    titleEn: "A week without social media", descriptionEn: "Delete the apps, and stay out of the browser too" },
  { id: "wis-solo-day", statType: "WIS", difficulty: "HARD", sortOrder: 73,
    title: "Bir günü yalnız geçir", description: "Plan yok, ekran yok, sadece sen",
    titleEn: "Spend a day alone", descriptionEn: "No plans, no screens, just you" },
  { id: "wis-screenfree-day", statType: "WIS", difficulty: "EPIC", sortOrder: 74,
    title: "Bir günü tamamen ekransız geçir", description: "Uyanıştan uykuya, acil durumlar hariç",
    titleEn: "Spend a whole day screen-free", descriptionEn: "Waking to sleeping, emergencies aside" },
  { id: "wis-retreat", statType: "WIS", difficulty: "EPIC", sortOrder: 75,
    title: "Bir inzivaya katıl", description: "Sessizlik, meditasyon veya doğa kampı — en az iki gün",
    titleEn: "Go on a retreat", descriptionEn: "Silence, meditation or a wilderness camp: two days minimum" },

  { id: "cha-call-friend", statType: "CHA", difficulty: "EASY", sortOrder: 76,
    title: "Bir arkadaşını ara", description: "Mesaj değil, sesli konuş, en az 15 dakika",
    titleEn: "Call a friend", descriptionEn: "Voice, not text, and at least 15 minutes" },
  { id: "cha-compliment", statType: "CHA", difficulty: "EASY", sortOrder: 77,
    title: "Birine içten bir iltifat et", description: "Genel değil, spesifik olsun",
    titleEn: "Give someone a genuine compliment", descriptionEn: "Specific, not generic" },
  { id: "cha-thank-someone", statType: "CHA", difficulty: "EASY", sortOrder: 78,
    title: "Birine teşekkür et", description: "Mesaj değil, yüz yüze veya sesli",
    titleEn: "Thank someone properly", descriptionEn: "In person or by voice, not by text" },
  { id: "cha-reconnect", statType: "CHA", difficulty: "EASY", sortOrder: 79,
    title: "Uzun süredir görüşmediğin birine yaz", description: "Bahane arama, sadece yaz",
    titleEn: "Reach out to someone you have lost touch with", descriptionEn: "Do not wait for a reason" },
  { id: "cha-listen-fully", statType: "CHA", difficulty: "EASY", sortOrder: 80,
    title: "Birini sözünü kesmeden dinle", description: "Tavsiye verme, sadece dinle",
    titleEn: "Listen to someone without interrupting", descriptionEn: "No advice, just listen" },
  { id: "cha-talk-stranger", statType: "CHA", difficulty: "MEDIUM", sortOrder: 81,
    title: "Tanımadığın biriyle sohbet başlat", description: "Kasada, otobüste, kuyrukta",
    titleEn: "Start a conversation with a stranger", descriptionEn: "At the till, on the bus, in a queue" },
  { id: "cha-presentation-rehearsal", statType: "CHA", difficulty: "MEDIUM", sortOrder: 82,
    title: "Sunum provası yap", description: "Yüksek sesle, baştan sona, kamera karşısında",
    titleEn: "Rehearse a presentation", descriptionEn: "Out loud, start to finish, on camera" },
  { id: "cha-host-meal", statType: "CHA", difficulty: "MEDIUM", sortOrder: 83,
    title: "Birini yemeğe davet et", description: "Sen pişir, sen ağırla",
    titleEn: "Host someone for a meal", descriptionEn: "You cook, you host" },
  { id: "cha-negotiate", statType: "CHA", difficulty: "MEDIUM", sortOrder: 84,
    title: "Bir pazarlık yap", description: "Fiyat, şart, zam — konuş ve iste",
    titleEn: "Negotiate something", descriptionEn: "A price, a term, a raise: ask for it" },
  { id: "cha-organise-meetup", statType: "CHA", difficulty: "MEDIUM", sortOrder: 85,
    title: "Bir buluşma organize et", description: "Sen çağır, sen planla, gerçekleşsin",
    titleEn: "Organise a get-together", descriptionEn: "You invite, you plan, it happens" },
  { id: "cha-public-speaking", statType: "CHA", difficulty: "HARD", sortOrder: 86,
    title: "Topluluk önünde konuş", description: "Toplantı, seminer, etkinlik — en az 10 kişi",
    titleEn: "Speak in front of a crowd", descriptionEn: "A meeting, a seminar, an event: at least 10 people" },
  { id: "cha-apologize", statType: "CHA", difficulty: "HARD", sortOrder: 87,
    title: "Gerçek bir özür dile", description: "Savunma yok, gerekçe yok, sadece özür",
    titleEn: "Apologise properly", descriptionEn: "No defence, no excuses, just the apology" },
  { id: "cha-new-group", statType: "CHA", difficulty: "HARD", sortOrder: 88,
    title: "Yeni bir gruba katıl", description: "Kulüp, takım, topluluk — ilk kez git",
    titleEn: "Join a new group", descriptionEn: "A club, a team, a community: show up for the first time" },
  { id: "cha-teach-workshop", statType: "CHA", difficulty: "EPIC", sortOrder: 89,
    title: "Bir atölye veya ders ver", description: "Hazırlan, sun, soruları karşıla",
    titleEn: "Run a workshop or class", descriptionEn: "Prepare it, deliver it, take the questions" },
  { id: "cha-lead-project", statType: "CHA", difficulty: "EPIC", sortOrder: 90,
    title: "Bir ekibe liderlik et", description: "Bir işi baştan sona sen yürüt, insanları taşı",
    titleEn: "Lead a team through a project", descriptionEn: "Own it end to end and carry the people with you" },
];

module.exports = { tasks };
