const pathways = [
  {
    id: "str_tier1",
    title: "Temel Kuvvet Yolu",
    description: "Vücudunu tanı, temeli at. Düzenli hareket alışkanlığı kazan.",
    titleEn: "The Foundation of Strength",
    descriptionEn: "Get to know your body and lay the groundwork. Build the habit of moving regularly.",
    primaryStat: "STR",
    secondaryStat: null,
    tier: 1,
    requiredPathwayId: null,
    completionBonusXp: 200,
    order: 1,
    quests: [
      { id: "str_tier1_q1", order: 1, stage: 1, statType: "STR", difficulty: "EASY", requiredCompletions: 5,
        title: "20 şınav çek", description: "Formunu bozmadan, tek sette",
        titleEn: "Do 20 push-ups", descriptionEn: "One set, without losing your form" },
      { id: "str_tier1_q2", order: 2, stage: 1, statType: "STR", difficulty: "EASY", requiredCompletions: 5,
        title: "15 dakika yürüyüş", description: "Tempolu, kesintisiz",
        titleEn: "Walk for 15 minutes", descriptionEn: "Brisk and unbroken" },
      { id: "str_tier1_q3", order: 3, stage: 1, statType: "STR", difficulty: "EASY", requiredCompletions: 5,
        title: "30 saniye plank", description: "Karnını sık, belini düz tut",
        titleEn: "Hold a 30-second plank", descriptionEn: "Brace your core, keep your back flat" },
      { id: "str_tier1_q4", order: 4, stage: 2, statType: "STR", difficulty: "MEDIUM", requiredCompletions: 4,
        title: "30 dk ağırlık antrenmanı", description: "Büyük kas gruplarına odaklan",
        titleEn: "30 minutes of weight training", descriptionEn: "Focus on the big muscle groups" },
      { id: "str_tier1_q5", order: 5, stage: 2, statType: "STR", difficulty: "MEDIUM", requiredCompletions: 3,
        title: "5 km koş", description: "Tempo önemli değil, mesafe önemli",
        titleEn: "Run 5 km", descriptionEn: "The pace does not matter, the distance does" },
      { id: "str_tier1_q6", order: 6, stage: 3, statType: "STR", difficulty: "HARD", requiredCompletions: 2,
        title: "Tam vücut antrenmanı", description: "En az 1 saat, tüm bölgeler",
        titleEn: "Full-body workout", descriptionEn: "At least an hour, every region" },
    ],
  },
  {
    id: "int_tier1",
    title: "Zihin Açıklığı Yolu",
    description: "Öğrenme kasını çalıştır. Odaklanma süreni uzat.",
    titleEn: "The Path of a Clear Mind",
    descriptionEn: "Work the learning muscle. Stretch how long you can focus.",
    primaryStat: "INT",
    secondaryStat: null,
    tier: 1,
    requiredPathwayId: null,
    completionBonusXp: 200,
    order: 2,
    quests: [
      { id: "int_tier1_q1", order: 1, stage: 1, statType: "INT", difficulty: "EASY", requiredCompletions: 5,
        title: "20 sayfa oku", description: "Kurgu dışı tercih et",
        titleEn: "Read 20 pages", descriptionEn: "Non-fiction preferred" },
      { id: "int_tier1_q2", order: 2, stage: 1, statType: "INT", difficulty: "EASY", requiredCompletions: 5,
        title: "Öğrendiklerini not al", description: "Kendi cümlelerinle özetle",
        titleEn: "Take notes on what you learned", descriptionEn: "Summarise it in your own words" },
      { id: "int_tier1_q3", order: 3, stage: 2, statType: "INT", difficulty: "MEDIUM", requiredCompletions: 4,
        title: "1 saat kesintisiz çalış", description: "Telefon uzakta, tek konu",
        titleEn: "Work an hour without a break", descriptionEn: "Phone out of reach, one subject" },
      { id: "int_tier1_q4", order: 4, stage: 2, statType: "INT", difficulty: "MEDIUM", requiredCompletions: 3,
        title: "Bir konuyu birine anlat", description: "Anlatabiliyorsan anlamışsındır",
        titleEn: "Explain a topic to someone", descriptionEn: "If you can teach it, you understand it" },
      { id: "int_tier1_q5", order: 5, stage: 3, statType: "INT", difficulty: "HARD", requiredCompletions: 2,
        title: "Küçük bir proje bitir", description: "Öğrendiğini uygula",
        titleEn: "Finish a small project", descriptionEn: "Put what you learned to use" },
    ],
  },
  {
    id: "wis_tier1",
    title: "İç Denge Yolu",
    description: "Zihnini sakinleştir, kendini gözlemle.",
    titleEn: "The Path of Inner Balance",
    descriptionEn: "Quiet your mind and learn to watch yourself.",
    primaryStat: "WIS",
    secondaryStat: null,
    tier: 1,
    requiredPathwayId: null,
    completionBonusXp: 200,
    order: 3,
    quests: [
      { id: "wis_tier1_q1", order: 1, stage: 1, statType: "WIS", difficulty: "EASY", requiredCompletions: 7,
        title: "10 dk meditasyon", description: "Nefese odaklan",
        titleEn: "Meditate for 10 minutes", descriptionEn: "Follow the breath" },
      { id: "wis_tier1_q2", order: 2, stage: 1, statType: "WIS", difficulty: "EASY", requiredCompletions: 7,
        title: "Günlük yaz", description: "Bugün ne oldu, ne hissettin",
        titleEn: "Write in your journal", descriptionEn: "What happened today, and how it felt" },
      { id: "wis_tier1_q3", order: 3, stage: 2, statType: "WIS", difficulty: "MEDIUM", requiredCompletions: 5,
        title: "Ekransız 2 saat geçir", description: "Telefon, bilgisayar, TV yok",
        titleEn: "Go two hours without a screen", descriptionEn: "No phone, no computer, no TV" },
      { id: "wis_tier1_q4", order: 4, stage: 2, statType: "WIS", difficulty: "MEDIUM", requiredCompletions: 4,
        title: "Yürüyüş meditasyonu", description: "45 dk, müziksiz, sadece yürü",
        titleEn: "Walking meditation", descriptionEn: "45 minutes, no music, just walk" },
    ],
  },
  {
    id: "cha_int_tier1",
    title: "İnsan Doğası Yolu",
    description: "İnsanları anlamayı ve kendini ifade etmeyi öğren.",
    titleEn: "The Path of Human Nature",
    descriptionEn: "Learn to read people and to make yourself understood.",
    primaryStat: "CHA",
    secondaryStat: "INT",
    tier: 1,
    requiredPathwayId: null,
    completionBonusXp: 250,
    order: 4,
    quests: [
      { id: "cha_int_tier1_q1", order: 1, stage: 1, statType: "CHA", difficulty: "EASY", requiredCompletions: 5,
        title: "Bir arkadaşını ara", description: "Mesaj değil, sesli konuş",
        titleEn: "Call a friend", descriptionEn: "Voice, not text" },
      { id: "cha_int_tier1_q2", order: 2, stage: 1, statType: "INT", difficulty: "EASY", requiredCompletions: 5,
        title: "Psikoloji üzerine 20 sayfa oku", description: "Davranış, biliş, motivasyon",
        titleEn: "Read 20 pages on psychology", descriptionEn: "Behaviour, cognition, motivation" },
      { id: "cha_int_tier1_q3", order: 3, stage: 2, statType: "INT", difficulty: "MEDIUM", requiredCompletions: 3,
        title: "Bir tartışmada karşı tarafı savun", description: "Kendi görüşünün tersini savun",
        titleEn: "Argue the opposing side", descriptionEn: "Make the case against your own view" },
      { id: "cha_int_tier1_q4", order: 4, stage: 2, statType: "CHA", difficulty: "MEDIUM", requiredCompletions: 4,
        title: "Sunum provası yap", description: "Yüksek sesle, baştan sona",
        titleEn: "Rehearse a presentation", descriptionEn: "Out loud, start to finish" },
      { id: "cha_int_tier1_q5", order: 5, stage: 3, statType: "CHA", difficulty: "HARD", requiredCompletions: 2,
        title: "Topluluk önünde konuş", description: "Toplantı, seminer, etkinlik",
        titleEn: "Speak in front of a crowd", descriptionEn: "A meeting, a seminar, an event" },
    ],
  },
  {
    id: "str_tier2",
    title: "Demir İrade Yolu",
    description: "Temeli attın. Şimdi sınırlarını zorla.",
    titleEn: "The Path of Iron Will",
    descriptionEn: "The groundwork is laid. Now push against your limits.",
    primaryStat: "STR",
    secondaryStat: "CON",
    tier: 2,
    requiredPathwayId: "str_tier1",
    completionBonusXp: 500,
    order: 5,
    quests: [
      { id: "str_tier2_q1", order: 1, stage: 1, statType: "STR", difficulty: "MEDIUM", requiredCompletions: 5,
        title: "50 şınav çek", description: "Tek sette olmasa da olur",
        titleEn: "Do 50 push-ups", descriptionEn: "Sets are fine" },
      { id: "str_tier2_q2", order: 2, stage: 1, statType: "CON", difficulty: "MEDIUM", requiredCompletions: 7,
        title: "8 saat uyu", description: "Toparlanma antrenmanın parçası",
        titleEn: "Sleep eight hours", descriptionEn: "Recovery is part of the training" },
      { id: "str_tier2_q3", order: 3, stage: 2, statType: "STR", difficulty: "HARD", requiredCompletions: 3,
        title: "10 km koş", description: "Tek seferde",
        titleEn: "Run 10 km", descriptionEn: "In one go" },
      { id: "str_tier2_q4", order: 4, stage: 3, statType: "STR", difficulty: "EPIC", requiredCompletions: 1,
        title: "Bir günlük fiziksel meydan okuma", description: "Yürüyüş, tırmanış, uzun antrenman",
        titleEn: "A day-long physical challenge", descriptionEn: "A hike, a climb, a long session" },
    ],
  },
];

module.exports = { pathways };
